export const REGISTER_PROCESS='REGISTER_PROCESS'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'

export const LOGIN_PROCESS='LOGIN_PROCESS'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAIL='LOGIN_FAIL'

export const ADMIN_LOGIN_PROCESS='ADMIN_LOGIN_PROCESS'
export const ADMIN_LOGIN_SUCCESS='ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL='ADMIN_LOGIN_FAIL'

export const RESULT_PROCESS='RESULT_PROCESS'
export const RESULT_SUCCESS='RESULT_SUCCESS'
export const RESULT_FAIL='RESULT_FAIL'

export const RESULT_LIST_PROCESS='RESULT_LIST_PROCESS'
export const RESULT_LIST_SUCCESS='RESULT_LIST_SUCCESS'
export const RESULT_LIST_FAIL='RESULT_LIST_FAIL'

export const NOTICE_PROCESS='NOTICE_PROCESS'
export const NOTICE_SUCCESS='NOTICE_SUCCESS'
export const NOTICE_FAIL=' NOTICE_FAIL'

export const NOTICE_LIST_PROCESS='NOTICE_LIST_PROCESS'
export const NOTICE_LIST_SUCCESS='NOTICE_LIST_SUCCESS'
export const NOTICE_LIST_FAIL=' NOTICE_LIST_FAIL'

export const DELETE_NOTICE_PROCESS='DELETE_NOTICE_PROCESS'
export const DELETE_NOTICE='DELETE_NOTICE'

export const UPDATE_NOTICE_PROCESS='UPDATE_NOTICE_PROCESS'
export const UPDATE_NOTICE='UPDATE_NOTICE'

export const LOGOUT='LOGOUT'

export const CONTUCT_LOADING='CONTUCT_LOADING'
export const CONTUCT_SUCCESS='CONTUCT_SUCCESS'
export const CONTUCT_FAIL='CONTUCT_FAIL'

export const CONTUCT_LIST_LOADING='CONTUCT_LIST_LOADING'
export const CONTUCT_LIST_SUCCESS='CONTUCT_LIST_SUCCESS'
export const CONTUCT_LIST_FAIL='CONTUCT_LIST_FAIL'

export const DETELE_CONTUCT_LOADING='DETELE_CONTUCT_LOADING'
export const  DETELE_CONTUCT_SUCCESS='DETELE_CONTUCT_SUCCESS'
export const  DETELE_CONTUCT_FAIL='DETELE_CONTUCT_FAIL'

export const PAYMENT_LOADING='PAYMENT_LOADING'
export const PAYMENT_SUCCESS='PAYMENT_SUCCESS'
export const PAYMENT_FAIL='PAYMENT_FAIL'

export const PAYMENT_LIST_LOADING='PAYMENT_LIST_LOADING'
export const PAYMENT_LIST_SUCCESS='PAYMENT_LIST_SUCCESS'
export const PAYMENT_LIST_FAIL='PAYMENT_LIST_FAIL'

export const PAYMENT_DELETE_LOADING='PAYMENT_DELETE_LOADING'
export const PAYMENT_DELETE_SUCCESS='PAYMENT_DELETE_SUCCESS'
export const PAYMENT_DELETE_FAIL='PAYMENT_DELETE_FAIL'


export const YOUTUBE_VIDEO_LOADING='YOUTUBE_VIDEO_LOADING'
export const YOUTUBE_VIDEO_SUCCESS='YOUTUBE_VIDEO_SUCCESS'
export const YOUTUBE_VIDEO_FAIL='YOUTUBE_VIDEO_FAIL'

export const YOUTUBELIST_VIDEO_LOADING='YOUTUBELIST_VIDEO_LOADING'
export const YOUTUBELIST_VIDEO_SUCCESS='YOUTUBELIST_VIDEO_SUCCESS'
export const YOUTUBELIST_VIDEO_FAIL='YOUTUBELIST_VIDEO_FAIL'

export const DELETE_VIDEO_LOADING='YOUTUBE_VIDEO_LOADING'
export const DELETE_VIDEO_SUCCESS='YOUTUBE_VIDEO_SUCCESS'
export const DELETE_VIDEO_FAIL='YOUTUBE_VIDEO_FAIL'

export const IMAGE_LOADING='IMAGE_LOADING'
export const IMAGE_SUCCESS='IMAGE_SUCCESS'
export const IMAGE_FAIL='IMAGE_FAIL'

export const GET_IMAGE_LOADING='GET_IMAGE_LOADING'
export const GET_IMAGE_SUCCESS='GET_IMAGE_SUCCESS'
export const GET_IMAGE_FAIL='GET_IMAGE_FAIL'

export const DELETE_IMAGE_LOADING='DELETE_IMAGE_LOADING'
export const DELETE_IMAGE_SUCCESS='DELETE_IMAGE_SUCCESS'
export const DELETE_IMAGE_FAIL='DELETE_IMAGE_FAIL'


export const IMAGE_DES_LOADING='IMAGE_DES_LOADING'
export const IMAGE_DES_SUCCESS='IMAGE_DES_SUCCESS'
export const IMAGE_DES_FAIL='IMAGE_DES_FAIL'

export const GET_IMAGE_DES_LOADING='GET_IMAGE_DES_LOADING'
export const GET_IMAGE_DES_SUCCESS='GET_IMAGE_DES_SUCCESS'
export const GET_IMAGE_DES_FAIL='GET_IMAGE_DES_FAIL'

export const DELETE_IMAGE_DES_LOADING='DELETE_IMAGE_DES_LOADING'
export const DELETE_IMAGE_DES_SUCCESS='DELETE_IMAGE_DES_SUCCESS'
export const DELETE_IMAGE_DES_FAIL='DELETE_IMAGE_DES_FAIL'

export const UPDATE_USER_LOADING='UPDATE_USER_LOADING'
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL='UPDATE_USER_FAIL'


export const EVENT_IMAGE_LOADING='EVENT_IMAGE_LOADING'
export const EVENT_IMAGE_SUCCESS='EVENT_IMAGE_SUCCESS'
export const EVENT_IMAGE_FAIL='EVENT_IMAGE_FAIL'

export const GET_EVENT_IMAGE_LOADING='GET_EVENT_IMAGE_LOADING'
export const GET_EVENT_IMAGE_SUCCESS='GET_EVENT_IMAGE_SUCCESS'
export const GET_EVENT_IMAGE_FAIL='GET_EVENT_IMAGE_FAIL'

export const DELETE_EVENT_IMAGE_LOADING='DELETE_EVENT_IMAGE_LOADING'
export const DELETE_EVENT_IMAGE_SUCCESS='DELETE_EVENT_IMAGE_SUCCESS'
export const DELETE_EVENT_IMAGE_FAIL='DELETE_EVENT_IMAGE_FAIL'


export const EVENT_IMAGE_DES_LOADING='EVENT_IMAGE_DES_LOADING'
export const EVENT_IMAGE_DES_SUCCESS='EVENT_IMAGE_DES_SUCCESS'
export const EVENT_IMAGE_DES_FAIL='EVENT_IMAGE_DES_FAIL'

export const GET_EVENT_IMAGE_DES_LOADING='GET_EVENT_IMAGE_DES_LOADING'
export const GET_EVENT_IMAGE_DES_SUCCESS='GET_EVENT_IMAGE_DES_SUCCESS'
export const GET_EVENT_IMAGE_DES_FAIL='GET_EVENT_IMAGE_DES_FAIL'

export const DELETE_EVENT_IMAGE_DES_LOADING='DELETE_EVENT_IMAGE_DES_LOADING'
export const DELETE_EVENT_IMAGE_DES_SUCCESS='DELETE_EVENT_IMAGE_DES_SUCCESS'
export const DELETE_EVENT_IMAGE_DES_FAIL='DELETE_EVENT_IMAGE_DES_FAIL'
